name: Certiport Checker Bot

on:
  schedule:
    - cron: '0 4 * * *' # Har kuni Toshkent vaqti bilan 09:00 da
  workflow_dispatch: # Qo'lda ishga tushirish tugmasi

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install selenium requests webdriver-manager

      - name: Run bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python bot.py

      - name: Upload Error Screenshot
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: error-screenshot
          path: debug_error.png
