name: Certiport Slot Checker

on:
  schedule:
    - cron: '*/20 * * * *' # Har 20 daqiqada avtomatik ishlaydi
  workflow_dispatch: # Qo'lda ishga tushirish uchun

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Kodni yuklash
        uses: actions/checkout@v3

      - name: Python 3.9 sozlash
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Kutubxonalarni o'rnatish
        run: pip install selenium requests webdriver-manager

      - name: Botni ishga tushirish
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python main.py
